export const EMAIL_FIELD_CHANGE = 'EMAIL_FIELD_CHANGE';
export const PASS_FIELD_CHANGE = 'PASS_FIELD_CHANGE';
export const LOGIN = 'LOGIN';

export const USER_FIELD_CHANGE = 'USER_FIELD_CHANGE';
export const SIGNUP = 'SIGNUP';
